name: CSPlugin
main: com.stpaulsmodding.csplugin.CSPlugin
version: 1.0
description: >
             The airship minigame plugin.
commands:
  airships:
    description: The base command of the airship minigame plugin.
